sudo: false
language: php

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=1.5.8
  - MONGO_VERSION=stable

addons:
  apt:
    sources:
    - mongodb-upstart
    packages:
    - mongodb-org-server

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION}
  - composer self-update
  - composer update --no-interaction --prefer-source

script:
    - phpunit --coverage-clover=coverage.clover
